Adding user app
Arseniks/education_time_management pull request #4
Opened 2023-07-19 09:53 UTC by Arseniks

Добавление .env файла
Добавление работы с Postgree
Добавление приложения user с моделью пользователя

2023-07-19 18:17 UTC, Fukurokouji commented on education_time_management/users/database.py
> +DATABASE_URL = DB_CONNECTION_URI
зачем

2023-07-19 18:26 UTC, Fukurokouji requested changes

2023-07-19 18:26 UTC, Fukurokouji commented on education_time_management/users/database.py
> +engine = create_engine(DATABASE_URL)
лучше засунуть все в один класс, под капотом которого будет инициализироваться энжайн к базе, и который будет следить, чтобы у тебя был один инстанс у фабрики сессий/создания подключения к базе

2023-07-19 18:26 UTC, Fukurokouji commented on pyproject.toml
> +fastapi-users = "^12.1.0"
я бы взял асинхронный драйвер для посгреса (asyncpg) + в зависимости лучше добавить бинарную сборку драйвера psycopg2(вроде у обычной версии есть проблема с совместимостью)

2023-07-19 18:26 UTC, Fukurokouji commented on education_time_management/app/config.py
> +DB_CONNECTION_URI = os.environ.get("DB_CONNECTION_URI", "postgresql://postgres:postgres@localhost:5432/dev_db")
лучше конфигурацию всех настроек засунуть в один класс, тем более у пидантика есть удобный инструмент под это (BaseSettings класс)

2023-07-19 18:26 UTC, Fukurokouji commented on education_time_management/users/database.py
> +class User(SQLAlchemyBaseUserTable[int], Base):
SQLAlchemyBaseUserTable[int] - непонятно зачем наследоваться от этого класса

2023-07-19 18:26 UTC, Fukurokouji commented on education_time_management/users/database.py
> +Base: DeclarativeMeta = declarative_base()
я бы добавил bindings для удобного чтения автонагенеренных запросов/миграций

2023-07-19 18:26 UTC, Fukurokouji commented on education_time_management/users/models.py
> +    Column("id", Integer, primary_key=True),
я бы айдишники у юзера делал бы на строковых идентификаторах(например uuid, желательно 7-ой версии)

2023-07-27 07:59 UTC, D1midr0sh approved these changes

2023-07-27 17:36 UTC, aeonva1ues commented on education_time_management/users/schemas.py
https://fastapi.tiangolo.com/tutorial/sql-databases/#__tabbed_1_1

Посмотри на пример схем в доке, идея с вынесением базового класса кажется полезной
Как минимум, не будет повторения полей

2023-07-27 17:42 UTC, aeonva1ues commented on education_time_management/users/schemas.py
https://fastapi.tiangolo.com/tutorial/sql-databases/#__tabbed_3_1

Я про orm_mode, думаю есть смысл в нем

2023-07-27 17:42 UTC, aeonva1ues approved these changes

2023-07-28 17:17 UTC, merged